language: generic
sudo: required
services:
  - docker

before_install
  - docker build -t sjm2932/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sjm2932/docker-react npm run test -- --coverage
